### ISSUE TITLE
Install under F24 failed

### ISSUE THREAD

**Issue by bugabinga** [phracek/dap-google-android-studio#3]
Tried to follow https://developer.fedoraproject.org/start/sw/mobile-app/mobile-devassistant.html.

```
[oliver@laptop android]$ da crt android-studio --name myandroid
INFO: Resolving RPM dependencies with DNF...
ERROR: Error resolving RPM dependencies with DNF: package ncurses-devel-6.0-5.20160116.fc24.i686 requires ncurses-libs(x86-32) = 6.0-5.20160116.fc24, but none of the providers can be installed.
package glibc-devel-2.23.1-7.fc24.i686 requires glibc = 2.23.1-7.fc24, but none of the providers can be installed
```

Workaround:

`dnf install compat-libstdc++-296 compat-libstdc++-33 glibc libgcc nss-softokn-freebl libstdc++ ncurses-libs zlib-devel.i686 ncurses-devel.i686 ant`

Discovered here http://stackoverflow.com/a/34568682. I don't know if all packages are required, but I assume all are necessary sooner or later for android development.

**Comment by sjug** [comment]
Workaround didn't work for me, I still get the error:

```
INFO: Resolving RPM dependencies with DNF...
ERROR: Error resolving RPM dependencies with DNF: package glibc-devel-2.23.1-7.fc24.i686 requires glibc = 2.23.1-7.fc24, but none of the providers can be installed
```

**Comment by Yky** [comment]
I had this as well. Installing glibc manually and then repeating your command. 

```
dnf install glibc.i686
da crt android-studio --name myandroid
```
